In [8]:
import pandas as pd

In [9]:
state_df = pd.read_csv('uscitiesv.csv')

In [10]:
state_df = state_df[['state_id','state_name']]

In [11]:
state_df['comb'] = state_df['state_id'] + state_df['state_name']

In [12]:
df = pd.DataFrame(state_df.comb.unique())

In [13]:
df.to_csv('states.csv')

In [14]:
df

                         0
0           PAPennsylvania
1                ALAlabama
2              LALouisiana
3                GAGeorgia
4            MSMississippi
5         SCSouth Carolina
6              WIWisconsin
7               VAVirginia
8          WVWest Virginia
9             NMNew Mexico
10                 TXTexas
11              ARArkansas
12        NCNorth Carolina
13                KSKansas
14          NDNorth Dakota
15            WAWashington
16               INIndiana
17                 IDIdaho
18              MDMaryland
19                  OHOhio
20              KYKentucky
21          SDSouth Dakota
22              NENebraska
23              ILIllinois
24                  IAIowa
25         MAMassachusetts
26                  UTUtah
27               MTMontana
28            NJNew Jersey
29            CACalifornia
30              NYNew York
31           PRPuerto Rico
32              OKOklahoma
33               WYWyoming
34                NVNevada
35              COColorado
36             MNMinnesota
37                OROregon
38                AKAlaska
39             TNTennessee
40                 MEMaine
41              MIMichigan
42              MOMissouri
43               AZArizona
44               FLFlorida
45               VTVermont
46         NHNew Hampshire
47                HIHawaii
48           CTConnecticut
49              DEDelaware
50          RIRhode Island
51        VIVirgin Islands
52  DCDistrict of Columbia